name: Publish to Itch.io

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION_DASH: "4.3-stable"
  GODOT_VERSION_DOT: "4.3.stable"


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and set up Godot
        run: |
          GODOT_URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION_DASH}/Godot_v${GODOT_VERSION_DASH}_linux.x86_64.zip"
          curl -L --retry 5 --retry-delay 10 --max-time 300 -o godot.zip $GODOT_URL
          unzip godot.zip -d godot
          sudo mv godot/Godot_v${GODOT_VERSION_DASH}_linux.x86_64 /usr/local/bin/godot
          sudo chmod +x /usr/local/bin/godot

      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION_DOT}
          cp -r .godot/export_templates/${GODOT_VERSION_DASH}/* ~/.local/share/godot/export_templates/${GODOT_VERSION_DOT}/

      - name: Export HTML5
        run: |
          mkdir -p build/web
          chmod -R 777 build
          godot --headless --export-release "Web" build/web/index.html

      - name: Zip exported files
        run: |
          zip -r build/web.zip build/web

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin/butler
          sudo chmod +x /usr/local/bin/butler

      - name: Push to Itch.io
        run: |
          butler push build/web.zip glasstacojar/1:"HTML5 / Playable in browser"
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
