name: Publish to Itch.io

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and set up Godot
        env:
          GODOT_VERSION: "4.3-stable"
        run: |
          GODOT_URL="https://downloads.tuxfamily.org/godotengine/4.3/Godot_v${GODOT_VERSION}_linux.x86_64.zip"
          curl -L $GODOT_URL --output godot.zip
          unzip godot.zip -d godot
          sudo mv godot/Godot_v${GODOT_VERSION}_linux.x86_64 /usr/local/bin/godot
          sudo chmod +x /usr/local/bin/godot
          godot --version

      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}
          cp -r .godot/export_templates/${GODOT_VERSION}/* ~/.local/share/godot/export_templates/${GODOT_VERSION}/

      - name: Export HTML5
        run: |
          godot --headless --export-release "Web" build/web
          ls -R build/web

      - name: Zip exported files
        run: |
          zip -r build/web.zip build/web
          ls -lh build/web.zip

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/head/butler.zip
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin/butler
          sudo chmod +x /usr/local/bin/butler
          butler -V

      - name: Push to Itch.io
        run: |
          butler push build/web.zip glasstacojar/gwj75:"HTML5 / Playable in browser"
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
