name: Publish to Itch.io

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Setup Node.js for compatibility
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Checkout the code from the main branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Download and set up Godot
      - name: Download and set up Godot
        env:
          GODOT_VERSION: "4.3-stable"
        run: |
          GODOT_URL="https://downloads.tuxfamily.org/godotengine/4.3/godot-${GODOT_VERSION}.tar.xz"
          echo "Downloading Godot from $GODOT_URL"
          curl -L $GODOT_URL --output godot.tar.xz
          mkdir -p godot
          tar -xf godot.tar.xz -C godot --strip-components=1
          sudo mv godot/godot* /usr/local/bin/godot
          sudo chmod +x /usr/local/bin/godot  # Make Godot executable
          godot --version  # Verify installation

      # Export the project for HTML5
      - name: Export HTML5
        run: |
          echo "Exporting project for Web..."
          godot --headless --export-release "Web" build/web
          ls -R build/web  # Verify export success

      # Compress the exported files
      - name: Zip exported files
        run: |
          echo "Zipping exported files..."
          zip -r build/web.zip build/web
          ls -lh build/web.zip  # Verify zip success

      # Install Butler
      - name: Install Butler
        run: |
          echo "Installing Butler..."
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/head/butler.zip
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin/butler
          butler -V  # Verify installation

      # Push to Itch.io using Butler
      - name: Push to Itch.io
        run: |
          echo "Pushing to Itch.io..."
          butler push build/web.zip glasstacojar/gwj75:"HTML5 / Playable in browser"
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
