name: Publish to Itch.io

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the main branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Godot environment variables
      - name: Set up Godot executable
        env:
          GODOT_VERSION: "4.3-stable"
          GODOT_URL: "https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_linux_headless.64.zip"
        run: |
          curl -L $GODOT_URL --output godot.zip
          unzip godot.zip -d godot
          sudo mv godot/Godot_* /usr/local/bin/godot

      # Export the project for HTML5
      - name: Export HTML5
        run: |
          godot --headless --export-release "Web" build/web
        env:
          GODOT_PROJECT_DIR: ${{ github.workspace }}

      # Compress the exported files
      - name: Zip exported files
        run: zip -r build/web.zip build/web

      # Install Butler
      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/head/butler.zip
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin/butler

      # Push to Itch.io using Butler
      - name: Push to Itch.io
        run: butler push build/web.zip glasstacojar/gwj75:"HTML5 / Playable in browser"
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
